/*
 * This file is generated by jOOQ.
 */
package task.NewOpportunityPortal.db.tables.records;


import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import task.NewOpportunityPortal.db.tables.AbilityComment;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AbilityCommentRecord extends UpdatableRecordImpl<AbilityCommentRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 375729523;

    /**
     * Setter for <code>public.ability_comment.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ability_comment.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.ability_comment.text</code>.
     */
    public void setText(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ability_comment.text</code>.
     */
    public String getText() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AbilityComment.ABILITY_COMMENT.ID;
    }

    @Override
    public Field<String> field2() {
        return AbilityComment.ABILITY_COMMENT.TEXT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getText();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getText();
    }

    @Override
    public AbilityCommentRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AbilityCommentRecord value2(String value) {
        setText(value);
        return this;
    }

    @Override
    public AbilityCommentRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AbilityCommentRecord
     */
    public AbilityCommentRecord() {
        super(AbilityComment.ABILITY_COMMENT);
    }

    /**
     * Create a detached, initialised AbilityCommentRecord
     */
    public AbilityCommentRecord(Long id, String text) {
        super(AbilityComment.ABILITY_COMMENT);

        set(0, id);
        set(1, text);
    }
}
