/*
 * This file is generated by jOOQ.
 */
package task.NewOpportunityPortal.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import task.NewOpportunityPortal.db.tables.Chats;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatsRecord extends UpdatableRecordImpl<ChatsRecord> implements Record6<Long, Long, Long, String, Long[], Timestamp> {

    private static final long serialVersionUID = 1885605852;

    /**
     * Setter for <code>public.chats.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.chats.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.chats.creatorId</code>.
     */
    public void setCreatorid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.chats.creatorId</code>.
     */
    public Long getCreatorid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.chats.advertId</code>.
     */
    public void setAdvertid(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.chats.advertId</code>.
     */
    public Long getAdvertid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.chats.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.chats.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.chats.usersId</code>.
     */
    public void setUsersid(Long... value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.chats.usersId</code>.
     */
    public Long[] getUsersid() {
        return (Long[]) get(4);
    }

    /**
     * Setter for <code>public.chats.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.chats.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, String, Long[], Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, String, Long[], Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Chats.CHATS.ID;
    }

    @Override
    public Field<Long> field2() {
        return Chats.CHATS.CREATORID;
    }

    @Override
    public Field<Long> field3() {
        return Chats.CHATS.ADVERTID;
    }

    @Override
    public Field<String> field4() {
        return Chats.CHATS.NAME;
    }

    @Override
    public Field<Long[]> field5() {
        return Chats.CHATS.USERSID;
    }

    @Override
    public Field<Timestamp> field6() {
        return Chats.CHATS.CREATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCreatorid();
    }

    @Override
    public Long component3() {
        return getAdvertid();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public Long[] component5() {
        return getUsersid();
    }

    @Override
    public Timestamp component6() {
        return getCreatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCreatorid();
    }

    @Override
    public Long value3() {
        return getAdvertid();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public Long[] value5() {
        return getUsersid();
    }

    @Override
    public Timestamp value6() {
        return getCreatedAt();
    }

    @Override
    public ChatsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ChatsRecord value2(Long value) {
        setCreatorid(value);
        return this;
    }

    @Override
    public ChatsRecord value3(Long value) {
        setAdvertid(value);
        return this;
    }

    @Override
    public ChatsRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public ChatsRecord value5(Long... value) {
        setUsersid(value);
        return this;
    }

    @Override
    public ChatsRecord value6(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ChatsRecord values(Long value1, Long value2, Long value3, String value4, Long[] value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatsRecord
     */
    public ChatsRecord() {
        super(Chats.CHATS);
    }

    /**
     * Create a detached, initialised ChatsRecord
     */
    public ChatsRecord(Long id, Long creatorid, Long advertid, String name, Long[] usersid, Timestamp createdAt) {
        super(Chats.CHATS);

        set(0, id);
        set(1, creatorid);
        set(2, advertid);
        set(3, name);
        set(4, usersid);
        set(5, createdAt);
    }
}
