/*
 * This file is generated by jOOQ.
 */
package task.NewOpportunityPortal.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import task.NewOpportunityPortal.db.tables.Comments;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommentsRecord extends UpdatableRecordImpl<CommentsRecord> implements Record5<Long, Long, Long, String, Timestamp> {

    private static final long serialVersionUID = -415066993;

    /**
     * Setter for <code>public.comments.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.comments.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.comments.creatorId</code>.
     */
    public void setCreatorid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.comments.creatorId</code>.
     */
    public Long getCreatorid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.comments.advertId</code>.
     */
    public void setAdvertid(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.comments.advertId</code>.
     */
    public Long getAdvertid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.comments.text</code>.
     */
    public void setText(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.comments.text</code>.
     */
    public String getText() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.comments.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.comments.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, Long, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Comments.COMMENTS.ID;
    }

    @Override
    public Field<Long> field2() {
        return Comments.COMMENTS.CREATORID;
    }

    @Override
    public Field<Long> field3() {
        return Comments.COMMENTS.ADVERTID;
    }

    @Override
    public Field<String> field4() {
        return Comments.COMMENTS.TEXT;
    }

    @Override
    public Field<Timestamp> field5() {
        return Comments.COMMENTS.CREATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCreatorid();
    }

    @Override
    public Long component3() {
        return getAdvertid();
    }

    @Override
    public String component4() {
        return getText();
    }

    @Override
    public Timestamp component5() {
        return getCreatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCreatorid();
    }

    @Override
    public Long value3() {
        return getAdvertid();
    }

    @Override
    public String value4() {
        return getText();
    }

    @Override
    public Timestamp value5() {
        return getCreatedAt();
    }

    @Override
    public CommentsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CommentsRecord value2(Long value) {
        setCreatorid(value);
        return this;
    }

    @Override
    public CommentsRecord value3(Long value) {
        setAdvertid(value);
        return this;
    }

    @Override
    public CommentsRecord value4(String value) {
        setText(value);
        return this;
    }

    @Override
    public CommentsRecord value5(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public CommentsRecord values(Long value1, Long value2, Long value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommentsRecord
     */
    public CommentsRecord() {
        super(Comments.COMMENTS);
    }

    /**
     * Create a detached, initialised CommentsRecord
     */
    public CommentsRecord(Long id, Long creatorid, Long advertid, String text, Timestamp createdAt) {
        super(Comments.COMMENTS);

        set(0, id);
        set(1, creatorid);
        set(2, advertid);
        set(3, text);
        set(4, createdAt);
    }
}
