/*
 * This file is generated by jOOQ.
 */
package task.NewOpportunityPortal.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import task.NewOpportunityPortal.db.tables.UserAbility;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAbilityRecord extends UpdatableRecordImpl<UserAbilityRecord> implements Record5<Long, Long, Long, Integer, Timestamp> {

    private static final long serialVersionUID = 1409191643;

    /**
     * Setter for <code>public.user_ability.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_ability.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_ability.authorId</code>.
     */
    public void setAuthorid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_ability.authorId</code>.
     */
    public Long getAuthorid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.user_ability.userId</code>.
     */
    public void setUserid(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_ability.userId</code>.
     */
    public Long getUserid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.user_ability.assessment</code>.
     */
    public void setAssessment(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_ability.assessment</code>.
     */
    public Integer getAssessment() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.user_ability.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user_ability.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, Integer, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, Long, Integer, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserAbility.USER_ABILITY.ID;
    }

    @Override
    public Field<Long> field2() {
        return UserAbility.USER_ABILITY.AUTHORID;
    }

    @Override
    public Field<Long> field3() {
        return UserAbility.USER_ABILITY.USERID;
    }

    @Override
    public Field<Integer> field4() {
        return UserAbility.USER_ABILITY.ASSESSMENT;
    }

    @Override
    public Field<Timestamp> field5() {
        return UserAbility.USER_ABILITY.CREATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getAuthorid();
    }

    @Override
    public Long component3() {
        return getUserid();
    }

    @Override
    public Integer component4() {
        return getAssessment();
    }

    @Override
    public Timestamp component5() {
        return getCreatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getAuthorid();
    }

    @Override
    public Long value3() {
        return getUserid();
    }

    @Override
    public Integer value4() {
        return getAssessment();
    }

    @Override
    public Timestamp value5() {
        return getCreatedAt();
    }

    @Override
    public UserAbilityRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserAbilityRecord value2(Long value) {
        setAuthorid(value);
        return this;
    }

    @Override
    public UserAbilityRecord value3(Long value) {
        setUserid(value);
        return this;
    }

    @Override
    public UserAbilityRecord value4(Integer value) {
        setAssessment(value);
        return this;
    }

    @Override
    public UserAbilityRecord value5(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UserAbilityRecord values(Long value1, Long value2, Long value3, Integer value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAbilityRecord
     */
    public UserAbilityRecord() {
        super(UserAbility.USER_ABILITY);
    }

    /**
     * Create a detached, initialised UserAbilityRecord
     */
    public UserAbilityRecord(Long id, Long authorid, Long userid, Integer assessment, Timestamp createdAt) {
        super(UserAbility.USER_ABILITY);

        set(0, id);
        set(1, authorid);
        set(2, userid);
        set(3, assessment);
        set(4, createdAt);
    }
}
