/*
 * This file is generated by jOOQ.
 */
package task.NewOpportunityPortal.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import task.NewOpportunityPortal.db.Indexes;
import task.NewOpportunityPortal.db.Keys;
import task.NewOpportunityPortal.db.Public;
import task.NewOpportunityPortal.db.tables.records.AdvertsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Adverts extends TableImpl<AdvertsRecord> {

    private static final long serialVersionUID = 2080160345;

    /**
     * The reference instance of <code>public.adverts</code>
     */
    public static final Adverts ADVERTS = new Adverts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdvertsRecord> getRecordType() {
        return AdvertsRecord.class;
    }

    /**
     * The column <code>public.adverts.id</code>.
     */
    public final TableField<AdvertsRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.adverts.creatorId</code>.
     */
    public final TableField<AdvertsRecord, Long> CREATORID = createField(DSL.name("creatorId"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.adverts.categoryId</code>.
     */
    public final TableField<AdvertsRecord, Long> CATEGORYID = createField(DSL.name("categoryId"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.adverts.workersId</code>.
     */
    public final TableField<AdvertsRecord, Long[]> WORKERSID = createField(DSL.name("workersId"), org.jooq.impl.SQLDataType.BIGINT.getArrayDataType(), this, "");

    /**
     * The column <code>public.adverts.subject</code>.
     */
    public final TableField<AdvertsRecord, String> SUBJECT = createField(DSL.name("subject"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.adverts.info</code>.
     */
    public final TableField<AdvertsRecord, String> INFO = createField(DSL.name("info"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.adverts.linkToDoc</code>.
     */
    public final TableField<AdvertsRecord, String> LINKTODOC = createField(DSL.name("linkToDoc"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.adverts.statusId</code>.
     */
    public final TableField<AdvertsRecord, Long> STATUSID = createField(DSL.name("statusId"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.adverts.tagsId</code>.
     */
    public final TableField<AdvertsRecord, Long[]> TAGSID = createField(DSL.name("tagsId"), org.jooq.impl.SQLDataType.BIGINT.getArrayDataType(), this, "");

    /**
     * The column <code>public.adverts.amountOfMarks</code>.
     */
    public final TableField<AdvertsRecord, Long[]> AMOUNTOFMARKS = createField(DSL.name("amountOfMarks"), org.jooq.impl.SQLDataType.BIGINT.getArrayDataType(), this, "");

    /**
     * The column <code>public.adverts.averageMark</code>.
     */
    public final TableField<AdvertsRecord, Long> AVERAGEMARK = createField(DSL.name("averageMark"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.adverts.created_at</code>.
     */
    public final TableField<AdvertsRecord, Timestamp> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>public.adverts</code> table reference
     */
    public Adverts() {
        this(DSL.name("adverts"), null);
    }

    /**
     * Create an aliased <code>public.adverts</code> table reference
     */
    public Adverts(String alias) {
        this(DSL.name(alias), ADVERTS);
    }

    /**
     * Create an aliased <code>public.adverts</code> table reference
     */
    public Adverts(Name alias) {
        this(alias, ADVERTS);
    }

    private Adverts(Name alias, Table<AdvertsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Adverts(Name alias, Table<AdvertsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Adverts(Table<O> child, ForeignKey<O, AdvertsRecord> key) {
        super(child, key, ADVERTS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ADVERTS_PKEY);
    }

    @Override
    public UniqueKey<AdvertsRecord> getPrimaryKey() {
        return Keys.ADVERTS_PKEY;
    }

    @Override
    public List<UniqueKey<AdvertsRecord>> getKeys() {
        return Arrays.<UniqueKey<AdvertsRecord>>asList(Keys.ADVERTS_PKEY, Keys.ADVERTS_STATUSID_KEY);
    }

    @Override
    public List<ForeignKey<AdvertsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AdvertsRecord, ?>>asList(Keys.ADVERTS__FK_ADVERT_USER, Keys.ADVERTS__FK_ADVERT_CATEGORY, Keys.ADVERTS__FK_ADVERT_STATUS);
    }

    public User user() {
        return new User(this, Keys.ADVERTS__FK_ADVERT_USER);
    }

    public Category category() {
        return new Category(this, Keys.ADVERTS__FK_ADVERT_CATEGORY);
    }

    public Status status() {
        return new Status(this, Keys.ADVERTS__FK_ADVERT_STATUS);
    }

    @Override
    public Adverts as(String alias) {
        return new Adverts(DSL.name(alias), this);
    }

    @Override
    public Adverts as(Name alias) {
        return new Adverts(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Adverts rename(String name) {
        return new Adverts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Adverts rename(Name name) {
        return new Adverts(name, null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, Long, Long, Long[], String, String, String, Long, Long[], Long[], Long, Timestamp> fieldsRow() {
        return (Row12) super.fieldsRow();
    }
}
