/*
 * This file is generated by jOOQ.
 */
package task.NewOpportunityPortal.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import task.NewOpportunityPortal.db.Indexes;
import task.NewOpportunityPortal.db.Keys;
import task.NewOpportunityPortal.db.Public;
import task.NewOpportunityPortal.db.tables.records.Chats_Record;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chats_ extends TableImpl<Chats_Record> {

    private static final long serialVersionUID = 729078009;

    /**
     * The reference instance of <code>public.chats_</code>
     */
    public static final Chats_ CHATS_ = new Chats_();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Chats_Record> getRecordType() {
        return Chats_Record.class;
    }

    /**
     * The column <code>public.chats_.id</code>.
     */
    public final TableField<Chats_Record, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.chats_.creatorId</code>.
     */
    public final TableField<Chats_Record, Long> CREATORID = createField(DSL.name("creatorId"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.chats_.advertId</code>.
     */
    public final TableField<Chats_Record, Long> ADVERTID = createField(DSL.name("advertId"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.chats_.name</code>.
     */
    public final TableField<Chats_Record, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.chats_.usersId</code>.
     */
    public final TableField<Chats_Record, Long[]> USERSID = createField(DSL.name("usersId"), org.jooq.impl.SQLDataType.BIGINT.getArrayDataType(), this, "");

    /**
     * The column <code>public.chats_.created_at</code>.
     */
    public final TableField<Chats_Record, Timestamp> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>public.chats_</code> table reference
     */
    public Chats_() {
        this(DSL.name("chats_"), null);
    }

    /**
     * Create an aliased <code>public.chats_</code> table reference
     */
    public Chats_(String alias) {
        this(DSL.name(alias), CHATS_);
    }

    /**
     * Create an aliased <code>public.chats_</code> table reference
     */
    public Chats_(Name alias) {
        this(alias, CHATS_);
    }

    private Chats_(Name alias, Table<Chats_Record> aliased) {
        this(alias, aliased, null);
    }

    private Chats_(Name alias, Table<Chats_Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Chats_(Table<O> child, ForeignKey<O, Chats_Record> key) {
        super(child, key, CHATS_);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CHATS__PKEY);
    }

    @Override
    public UniqueKey<Chats_Record> getPrimaryKey() {
        return Keys.CHATS__PKEY;
    }

    @Override
    public List<UniqueKey<Chats_Record>> getKeys() {
        return Arrays.<UniqueKey<Chats_Record>>asList(Keys.CHATS__PKEY);
    }

    @Override
    public List<ForeignKey<Chats_Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Chats_Record, ?>>asList(Keys.CHATS___FK_CHAT_USER, Keys.CHATS___FK_CHAT_ADVERT);
    }

    public User user() {
        return new User(this, Keys.CHATS___FK_CHAT_USER);
    }

    public Adverts adverts() {
        return new Adverts(this, Keys.CHATS___FK_CHAT_ADVERT);
    }

    @Override
    public Chats_ as(String alias) {
        return new Chats_(DSL.name(alias), this);
    }

    @Override
    public Chats_ as(Name alias) {
        return new Chats_(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Chats_ rename(String name) {
        return new Chats_(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Chats_ rename(Name name) {
        return new Chats_(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, String, Long[], Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
