/*
 * This file is generated by jOOQ.
 */
package task.NewOpportunityPortal.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import task.NewOpportunityPortal.db.Indexes;
import task.NewOpportunityPortal.db.Keys;
import task.NewOpportunityPortal.db.Public;
import task.NewOpportunityPortal.db.tables.records.Comments_Record;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Comments_ extends TableImpl<Comments_Record> {

    private static final long serialVersionUID = -807731442;

    /**
     * The reference instance of <code>public.comments_</code>
     */
    public static final Comments_ COMMENTS_ = new Comments_();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Comments_Record> getRecordType() {
        return Comments_Record.class;
    }

    /**
     * The column <code>public.comments_.id</code>.
     */
    public final TableField<Comments_Record, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.comments_.creatorId</code>.
     */
    public final TableField<Comments_Record, Long> CREATORID = createField(DSL.name("creatorId"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.comments_.advertId</code>.
     */
    public final TableField<Comments_Record, Long> ADVERTID = createField(DSL.name("advertId"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.comments_.text</code>.
     */
    public final TableField<Comments_Record, String> TEXT = createField(DSL.name("text"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.comments_.created_at</code>.
     */
    public final TableField<Comments_Record, Timestamp> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>public.comments_</code> table reference
     */
    public Comments_() {
        this(DSL.name("comments_"), null);
    }

    /**
     * Create an aliased <code>public.comments_</code> table reference
     */
    public Comments_(String alias) {
        this(DSL.name(alias), COMMENTS_);
    }

    /**
     * Create an aliased <code>public.comments_</code> table reference
     */
    public Comments_(Name alias) {
        this(alias, COMMENTS_);
    }

    private Comments_(Name alias, Table<Comments_Record> aliased) {
        this(alias, aliased, null);
    }

    private Comments_(Name alias, Table<Comments_Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Comments_(Table<O> child, ForeignKey<O, Comments_Record> key) {
        super(child, key, COMMENTS_);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.COMMENTS__PKEY);
    }

    @Override
    public UniqueKey<Comments_Record> getPrimaryKey() {
        return Keys.COMMENTS__PKEY;
    }

    @Override
    public List<UniqueKey<Comments_Record>> getKeys() {
        return Arrays.<UniqueKey<Comments_Record>>asList(Keys.COMMENTS__PKEY);
    }

    @Override
    public List<ForeignKey<Comments_Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Comments_Record, ?>>asList(Keys.COMMENTS___FK_COMMENT_USER, Keys.COMMENTS___FK_COMMENT_ADVERT);
    }

    public User user() {
        return new User(this, Keys.COMMENTS___FK_COMMENT_USER);
    }

    public Adverts adverts() {
        return new Adverts(this, Keys.COMMENTS___FK_COMMENT_ADVERT);
    }

    @Override
    public Comments_ as(String alias) {
        return new Comments_(DSL.name(alias), this);
    }

    @Override
    public Comments_ as(Name alias) {
        return new Comments_(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Comments_ rename(String name) {
        return new Comments_(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Comments_ rename(Name name) {
        return new Comments_(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
