/*
 * This file is generated by jOOQ.
 */
package task.NewOpportunityPortal.db;


import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import task.NewOpportunityPortal.db.tables.AbilityComment;
import task.NewOpportunityPortal.db.tables.Adverts;
import task.NewOpportunityPortal.db.tables.Category;
import task.NewOpportunityPortal.db.tables.Chats;
import task.NewOpportunityPortal.db.tables.Comments;
import task.NewOpportunityPortal.db.tables.Messages;
import task.NewOpportunityPortal.db.tables.Status;
import task.NewOpportunityPortal.db.tables.Tag;
import task.NewOpportunityPortal.db.tables.User;
import task.NewOpportunityPortal.db.tables.UserAbility;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ABILITY_COMMENT_PKEY = Indexes0.ABILITY_COMMENT_PKEY;
    public static final Index ADVERTS_PKEY = Indexes0.ADVERTS_PKEY;
    public static final Index CATEGORY_NAME_KEY = Indexes0.CATEGORY_NAME_KEY;
    public static final Index CATEGORY_PKEY = Indexes0.CATEGORY_PKEY;
    public static final Index CHATS_PKEY = Indexes0.CHATS_PKEY;
    public static final Index COMMENTS_PKEY = Indexes0.COMMENTS_PKEY;
    public static final Index MESSAGES_PKEY = Indexes0.MESSAGES_PKEY;
    public static final Index STATUS_NAME_KEY = Indexes0.STATUS_NAME_KEY;
    public static final Index STATUS_PKEY = Indexes0.STATUS_PKEY;
    public static final Index TAG_NAME_KEY = Indexes0.TAG_NAME_KEY;
    public static final Index TAG_PKEY = Indexes0.TAG_PKEY;
    public static final Index USER_LOGIN_KEY = Indexes0.USER_LOGIN_KEY;
    public static final Index USER_NICK_KEY = Indexes0.USER_NICK_KEY;
    public static final Index USER_PKEY = Indexes0.USER_PKEY;
    public static final Index USER_ABILITY_PKEY = Indexes0.USER_ABILITY_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ABILITY_COMMENT_PKEY = Internal.createIndex("ability_comment_pkey", AbilityComment.ABILITY_COMMENT, new OrderField[] { AbilityComment.ABILITY_COMMENT.ID }, true);
        public static Index ADVERTS_PKEY = Internal.createIndex("adverts_pkey", Adverts.ADVERTS, new OrderField[] { Adverts.ADVERTS.ID }, true);
        public static Index CATEGORY_NAME_KEY = Internal.createIndex("category_name_key", Category.CATEGORY, new OrderField[] { Category.CATEGORY.NAME }, true);
        public static Index CATEGORY_PKEY = Internal.createIndex("category_pkey", Category.CATEGORY, new OrderField[] { Category.CATEGORY.ID }, true);
        public static Index CHATS_PKEY = Internal.createIndex("chats_pkey", Chats.CHATS, new OrderField[] { Chats.CHATS.ID }, true);
        public static Index COMMENTS_PKEY = Internal.createIndex("comments_pkey", Comments.COMMENTS, new OrderField[] { Comments.COMMENTS.ID }, true);
        public static Index MESSAGES_PKEY = Internal.createIndex("messages_pkey", Messages.MESSAGES, new OrderField[] { Messages.MESSAGES.ID }, true);
        public static Index STATUS_NAME_KEY = Internal.createIndex("status_name_key", Status.STATUS, new OrderField[] { Status.STATUS.NAME }, true);
        public static Index STATUS_PKEY = Internal.createIndex("status_pkey", Status.STATUS, new OrderField[] { Status.STATUS.ID }, true);
        public static Index TAG_NAME_KEY = Internal.createIndex("tag_name_key", Tag.TAG, new OrderField[] { Tag.TAG.NAME }, true);
        public static Index TAG_PKEY = Internal.createIndex("tag_pkey", Tag.TAG, new OrderField[] { Tag.TAG.ID }, true);
        public static Index USER_LOGIN_KEY = Internal.createIndex("user_login_key", User.USER, new OrderField[] { User.USER.LOGIN }, true);
        public static Index USER_NICK_KEY = Internal.createIndex("user_nick_key", User.USER, new OrderField[] { User.USER.NICK }, true);
        public static Index USER_PKEY = Internal.createIndex("user_pkey", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index USER_ABILITY_PKEY = Internal.createIndex("user_ability_pkey", UserAbility.USER_ABILITY, new OrderField[] { UserAbility.USER_ABILITY.ID }, true);
    }
}
