/*
 * This file is generated by jOOQ.
 */
package task.NewOpportunityPortal.db;


import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import task.NewOpportunityPortal.db.tables.AbilityComment;
import task.NewOpportunityPortal.db.tables.Adverts;
import task.NewOpportunityPortal.db.tables.Category;
import task.NewOpportunityPortal.db.tables.Chats;
import task.NewOpportunityPortal.db.tables.Comments;
import task.NewOpportunityPortal.db.tables.Messages;
import task.NewOpportunityPortal.db.tables.Status;
import task.NewOpportunityPortal.db.tables.Tag;
import task.NewOpportunityPortal.db.tables.User;
import task.NewOpportunityPortal.db.tables.UserAbility;
import task.NewOpportunityPortal.db.tables.records.AbilityCommentRecord;
import task.NewOpportunityPortal.db.tables.records.AdvertsRecord;
import task.NewOpportunityPortal.db.tables.records.CategoryRecord;
import task.NewOpportunityPortal.db.tables.records.ChatsRecord;
import task.NewOpportunityPortal.db.tables.records.CommentsRecord;
import task.NewOpportunityPortal.db.tables.records.MessagesRecord;
import task.NewOpportunityPortal.db.tables.records.StatusRecord;
import task.NewOpportunityPortal.db.tables.records.TagRecord;
import task.NewOpportunityPortal.db.tables.records.UserAbilityRecord;
import task.NewOpportunityPortal.db.tables.records.UserRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AbilityCommentRecord> ABILITY_COMMENT_PKEY = UniqueKeys0.ABILITY_COMMENT_PKEY;
    public static final UniqueKey<AdvertsRecord> ADVERTS_PKEY = UniqueKeys0.ADVERTS_PKEY;
    public static final UniqueKey<AdvertsRecord> ADVERTS_STATUSID_KEY = UniqueKeys0.ADVERTS_STATUSID_KEY;
    public static final UniqueKey<CategoryRecord> CATEGORY_PKEY = UniqueKeys0.CATEGORY_PKEY;
    public static final UniqueKey<CategoryRecord> CATEGORY_NAME_KEY = UniqueKeys0.CATEGORY_NAME_KEY;
    public static final UniqueKey<ChatsRecord> CHATS_PKEY = UniqueKeys0.CHATS_PKEY;
    public static final UniqueKey<CommentsRecord> COMMENTS_PKEY = UniqueKeys0.COMMENTS_PKEY;
    public static final UniqueKey<MessagesRecord> MESSAGES_PKEY = UniqueKeys0.MESSAGES_PKEY;
    public static final UniqueKey<StatusRecord> STATUS_PKEY = UniqueKeys0.STATUS_PKEY;
    public static final UniqueKey<StatusRecord> STATUS_NAME_KEY = UniqueKeys0.STATUS_NAME_KEY;
    public static final UniqueKey<TagRecord> TAG_PKEY = UniqueKeys0.TAG_PKEY;
    public static final UniqueKey<TagRecord> TAG_NAME_KEY = UniqueKeys0.TAG_NAME_KEY;
    public static final UniqueKey<UserRecord> USER_PKEY = UniqueKeys0.USER_PKEY;
    public static final UniqueKey<UserRecord> USER_LOGIN_KEY = UniqueKeys0.USER_LOGIN_KEY;
    public static final UniqueKey<UserRecord> USER_NICK_KEY = UniqueKeys0.USER_NICK_KEY;
    public static final UniqueKey<UserAbilityRecord> USER_ABILITY_PKEY = UniqueKeys0.USER_ABILITY_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AbilityCommentRecord, UserAbilityRecord> ABILITY_COMMENT__FK_ABILITY_COMMENT_USER = ForeignKeys0.ABILITY_COMMENT__FK_ABILITY_COMMENT_USER;
    public static final ForeignKey<AdvertsRecord, UserRecord> ADVERTS__FK_ADVERT_USER = ForeignKeys0.ADVERTS__FK_ADVERT_USER;
    public static final ForeignKey<AdvertsRecord, CategoryRecord> ADVERTS__FK_ADVERT_CATEGORY = ForeignKeys0.ADVERTS__FK_ADVERT_CATEGORY;
    public static final ForeignKey<AdvertsRecord, StatusRecord> ADVERTS__FK_ADVERT_STATUS = ForeignKeys0.ADVERTS__FK_ADVERT_STATUS;
    public static final ForeignKey<ChatsRecord, UserRecord> CHATS__FK_CHAT_USER = ForeignKeys0.CHATS__FK_CHAT_USER;
    public static final ForeignKey<ChatsRecord, AdvertsRecord> CHATS__FK_CHAT_ADVERT = ForeignKeys0.CHATS__FK_CHAT_ADVERT;
    public static final ForeignKey<CommentsRecord, UserRecord> COMMENTS__FK_COMMENT_USER = ForeignKeys0.COMMENTS__FK_COMMENT_USER;
    public static final ForeignKey<CommentsRecord, AdvertsRecord> COMMENTS__FK_COMMENT_ADVERT = ForeignKeys0.COMMENTS__FK_COMMENT_ADVERT;
    public static final ForeignKey<MessagesRecord, UserRecord> MESSAGES__FK_MESSAGE_USER = ForeignKeys0.MESSAGES__FK_MESSAGE_USER;
    public static final ForeignKey<MessagesRecord, ChatsRecord> MESSAGES__FK_MESSAGE_CHAT = ForeignKeys0.MESSAGES__FK_MESSAGE_CHAT;
    public static final ForeignKey<UserAbilityRecord, UserRecord> USER_ABILITY__FK_USER_ABILITY_AUTHOR = ForeignKeys0.USER_ABILITY__FK_USER_ABILITY_AUTHOR;
    public static final ForeignKey<UserAbilityRecord, UserRecord> USER_ABILITY__FK_USER_ABILITY_USER = ForeignKeys0.USER_ABILITY__FK_USER_ABILITY_USER;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AbilityCommentRecord> ABILITY_COMMENT_PKEY = Internal.createUniqueKey(AbilityComment.ABILITY_COMMENT, "ability_comment_pkey", AbilityComment.ABILITY_COMMENT.ID);
        public static final UniqueKey<AdvertsRecord> ADVERTS_PKEY = Internal.createUniqueKey(Adverts.ADVERTS, "adverts_pkey", Adverts.ADVERTS.ID);
        public static final UniqueKey<AdvertsRecord> ADVERTS_STATUSID_KEY = Internal.createUniqueKey(Adverts.ADVERTS, "adverts_statusId_key", Adverts.ADVERTS.STATUSID);
        public static final UniqueKey<CategoryRecord> CATEGORY_PKEY = Internal.createUniqueKey(Category.CATEGORY, "category_pkey", Category.CATEGORY.ID);
        public static final UniqueKey<CategoryRecord> CATEGORY_NAME_KEY = Internal.createUniqueKey(Category.CATEGORY, "category_name_key", Category.CATEGORY.NAME);
        public static final UniqueKey<ChatsRecord> CHATS_PKEY = Internal.createUniqueKey(Chats.CHATS, "chats_pkey", Chats.CHATS.ID);
        public static final UniqueKey<CommentsRecord> COMMENTS_PKEY = Internal.createUniqueKey(Comments.COMMENTS, "comments_pkey", Comments.COMMENTS.ID);
        public static final UniqueKey<MessagesRecord> MESSAGES_PKEY = Internal.createUniqueKey(Messages.MESSAGES, "messages_pkey", Messages.MESSAGES.ID);
        public static final UniqueKey<StatusRecord> STATUS_PKEY = Internal.createUniqueKey(Status.STATUS, "status_pkey", Status.STATUS.ID);
        public static final UniqueKey<StatusRecord> STATUS_NAME_KEY = Internal.createUniqueKey(Status.STATUS, "status_name_key", Status.STATUS.NAME);
        public static final UniqueKey<TagRecord> TAG_PKEY = Internal.createUniqueKey(Tag.TAG, "tag_pkey", Tag.TAG.ID);
        public static final UniqueKey<TagRecord> TAG_NAME_KEY = Internal.createUniqueKey(Tag.TAG, "tag_name_key", Tag.TAG.NAME);
        public static final UniqueKey<UserRecord> USER_PKEY = Internal.createUniqueKey(User.USER, "user_pkey", User.USER.ID);
        public static final UniqueKey<UserRecord> USER_LOGIN_KEY = Internal.createUniqueKey(User.USER, "user_login_key", User.USER.LOGIN);
        public static final UniqueKey<UserRecord> USER_NICK_KEY = Internal.createUniqueKey(User.USER, "user_nick_key", User.USER.NICK);
        public static final UniqueKey<UserAbilityRecord> USER_ABILITY_PKEY = Internal.createUniqueKey(UserAbility.USER_ABILITY, "user_ability_pkey", UserAbility.USER_ABILITY.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AbilityCommentRecord, UserAbilityRecord> ABILITY_COMMENT__FK_ABILITY_COMMENT_USER = Internal.createForeignKey(task.NewOpportunityPortal.db.Keys.USER_ABILITY_PKEY, AbilityComment.ABILITY_COMMENT, "ability_comment__fk_ability_comment_user", AbilityComment.ABILITY_COMMENT.ID);
        public static final ForeignKey<AdvertsRecord, UserRecord> ADVERTS__FK_ADVERT_USER = Internal.createForeignKey(task.NewOpportunityPortal.db.Keys.USER_PKEY, Adverts.ADVERTS, "adverts__fk_advert_user", Adverts.ADVERTS.CREATORID);
        public static final ForeignKey<AdvertsRecord, CategoryRecord> ADVERTS__FK_ADVERT_CATEGORY = Internal.createForeignKey(task.NewOpportunityPortal.db.Keys.CATEGORY_PKEY, Adverts.ADVERTS, "adverts__fk_advert_category", Adverts.ADVERTS.CATEGORYID);
        public static final ForeignKey<AdvertsRecord, StatusRecord> ADVERTS__FK_ADVERT_STATUS = Internal.createForeignKey(task.NewOpportunityPortal.db.Keys.STATUS_PKEY, Adverts.ADVERTS, "adverts__fk_advert_status", Adverts.ADVERTS.STATUSID);
        public static final ForeignKey<ChatsRecord, UserRecord> CHATS__FK_CHAT_USER = Internal.createForeignKey(task.NewOpportunityPortal.db.Keys.USER_PKEY, Chats.CHATS, "chats__fk_chat_user", Chats.CHATS.CREATORID);
        public static final ForeignKey<ChatsRecord, AdvertsRecord> CHATS__FK_CHAT_ADVERT = Internal.createForeignKey(task.NewOpportunityPortal.db.Keys.ADVERTS_PKEY, Chats.CHATS, "chats__fk_chat_advert", Chats.CHATS.ADVERTID);
        public static final ForeignKey<CommentsRecord, UserRecord> COMMENTS__FK_COMMENT_USER = Internal.createForeignKey(task.NewOpportunityPortal.db.Keys.USER_PKEY, Comments.COMMENTS, "comments__fk_comment_user", Comments.COMMENTS.CREATORID);
        public static final ForeignKey<CommentsRecord, AdvertsRecord> COMMENTS__FK_COMMENT_ADVERT = Internal.createForeignKey(task.NewOpportunityPortal.db.Keys.ADVERTS_PKEY, Comments.COMMENTS, "comments__fk_comment_advert", Comments.COMMENTS.ADVERTID);
        public static final ForeignKey<MessagesRecord, UserRecord> MESSAGES__FK_MESSAGE_USER = Internal.createForeignKey(task.NewOpportunityPortal.db.Keys.USER_PKEY, Messages.MESSAGES, "messages__fk_message_user", Messages.MESSAGES.CREATORID);
        public static final ForeignKey<MessagesRecord, ChatsRecord> MESSAGES__FK_MESSAGE_CHAT = Internal.createForeignKey(task.NewOpportunityPortal.db.Keys.CHATS_PKEY, Messages.MESSAGES, "messages__fk_message_chat", Messages.MESSAGES.CHATID);
        public static final ForeignKey<UserAbilityRecord, UserRecord> USER_ABILITY__FK_USER_ABILITY_AUTHOR = Internal.createForeignKey(task.NewOpportunityPortal.db.Keys.USER_PKEY, UserAbility.USER_ABILITY, "user_ability__fk_user_ability_author", UserAbility.USER_ABILITY.AUTHORID);
        public static final ForeignKey<UserAbilityRecord, UserRecord> USER_ABILITY__FK_USER_ABILITY_USER = Internal.createForeignKey(task.NewOpportunityPortal.db.Keys.USER_PKEY, UserAbility.USER_ABILITY, "user_ability__fk_user_ability_user", UserAbility.USER_ABILITY.USERID);
    }
}
