/*
 * This file is generated by jOOQ.
 */
package task.NewOpportunityPortal.db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import task.NewOpportunityPortal.db.tables.Adverts;
import task.NewOpportunityPortal.db.tables.Category;
import task.NewOpportunityPortal.db.tables.Chats_;
import task.NewOpportunityPortal.db.tables.Comments_;
import task.NewOpportunityPortal.db.tables.Messages__;
import task.NewOpportunityPortal.db.tables.Status;
import task.NewOpportunityPortal.db.tables.Tag;
import task.NewOpportunityPortal.db.tables.User;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 425717179;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.adverts</code>.
     */
    public final Adverts ADVERTS = task.NewOpportunityPortal.db.tables.Adverts.ADVERTS;

    /**
     * The table <code>public.category</code>.
     */
    public final Category CATEGORY = task.NewOpportunityPortal.db.tables.Category.CATEGORY;

    /**
     * The table <code>public.chats_</code>.
     */
    public final Chats_ CHATS_ = task.NewOpportunityPortal.db.tables.Chats_.CHATS_;

    /**
     * The table <code>public.comments_</code>.
     */
    public final Comments_ COMMENTS_ = task.NewOpportunityPortal.db.tables.Comments_.COMMENTS_;

    /**
     * The table <code>public.messages__</code>.
     */
    public final Messages__ MESSAGES__ = task.NewOpportunityPortal.db.tables.Messages__.MESSAGES__;

    /**
     * The table <code>public.status</code>.
     */
    public final Status STATUS = task.NewOpportunityPortal.db.tables.Status.STATUS;

    /**
     * The table <code>public.tag</code>.
     */
    public final Tag TAG = task.NewOpportunityPortal.db.tables.Tag.TAG;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = task.NewOpportunityPortal.db.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Adverts.ADVERTS,
            Category.CATEGORY,
            Chats_.CHATS_,
            Comments_.COMMENTS_,
            Messages__.MESSAGES__,
            Status.STATUS,
            Tag.TAG,
            User.USER);
    }
}
