/*
 * This file is generated by jOOQ.
 */
package task.NewOpportunityPortal.db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import task.NewOpportunityPortal.db.tables.AbilityComment;
import task.NewOpportunityPortal.db.tables.Adverts;
import task.NewOpportunityPortal.db.tables.Category;
import task.NewOpportunityPortal.db.tables.Chats;
import task.NewOpportunityPortal.db.tables.Comments;
import task.NewOpportunityPortal.db.tables.Messages;
import task.NewOpportunityPortal.db.tables.Status;
import task.NewOpportunityPortal.db.tables.Tag;
import task.NewOpportunityPortal.db.tables.User;
import task.NewOpportunityPortal.db.tables.UserAbility;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1303236039;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.ability_comment</code>.
     */
    public final AbilityComment ABILITY_COMMENT = task.NewOpportunityPortal.db.tables.AbilityComment.ABILITY_COMMENT;

    /**
     * The table <code>public.adverts</code>.
     */
    public final Adverts ADVERTS = task.NewOpportunityPortal.db.tables.Adverts.ADVERTS;

    /**
     * The table <code>public.category</code>.
     */
    public final Category CATEGORY = task.NewOpportunityPortal.db.tables.Category.CATEGORY;

    /**
     * The table <code>public.chats</code>.
     */
    public final Chats CHATS = task.NewOpportunityPortal.db.tables.Chats.CHATS;

    /**
     * The table <code>public.comments</code>.
     */
    public final Comments COMMENTS = task.NewOpportunityPortal.db.tables.Comments.COMMENTS;

    /**
     * The table <code>public.messages</code>.
     */
    public final Messages MESSAGES = task.NewOpportunityPortal.db.tables.Messages.MESSAGES;

    /**
     * The table <code>public.status</code>.
     */
    public final Status STATUS = task.NewOpportunityPortal.db.tables.Status.STATUS;

    /**
     * The table <code>public.tag</code>.
     */
    public final Tag TAG = task.NewOpportunityPortal.db.tables.Tag.TAG;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = task.NewOpportunityPortal.db.tables.User.USER;

    /**
     * The table <code>public.user_ability</code>.
     */
    public final UserAbility USER_ABILITY = task.NewOpportunityPortal.db.tables.UserAbility.USER_ABILITY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AbilityComment.ABILITY_COMMENT,
            Adverts.ADVERTS,
            Category.CATEGORY,
            Chats.CHATS,
            Comments.COMMENTS,
            Messages.MESSAGES,
            Status.STATUS,
            Tag.TAG,
            User.USER,
            UserAbility.USER_ABILITY);
    }
}
