/*
 * This file is generated by jOOQ.
 */
package task.NewOpportunityPortal.db;


import javax.annotation.processing.Generated;

import task.NewOpportunityPortal.db.tables.AbilityComment;
import task.NewOpportunityPortal.db.tables.Adverts;
import task.NewOpportunityPortal.db.tables.Category;
import task.NewOpportunityPortal.db.tables.Chats;
import task.NewOpportunityPortal.db.tables.Comments;
import task.NewOpportunityPortal.db.tables.Messages;
import task.NewOpportunityPortal.db.tables.Status;
import task.NewOpportunityPortal.db.tables.Tag;
import task.NewOpportunityPortal.db.tables.User;
import task.NewOpportunityPortal.db.tables.UserAbility;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.ability_comment</code>.
     */
    public static final AbilityComment ABILITY_COMMENT = AbilityComment.ABILITY_COMMENT;

    /**
     * The table <code>public.adverts</code>.
     */
    public static final Adverts ADVERTS = Adverts.ADVERTS;

    /**
     * The table <code>public.category</code>.
     */
    public static final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>public.chats</code>.
     */
    public static final Chats CHATS = Chats.CHATS;

    /**
     * The table <code>public.comments</code>.
     */
    public static final Comments COMMENTS = Comments.COMMENTS;

    /**
     * The table <code>public.messages</code>.
     */
    public static final Messages MESSAGES = Messages.MESSAGES;

    /**
     * The table <code>public.status</code>.
     */
    public static final Status STATUS = Status.STATUS;

    /**
     * The table <code>public.tag</code>.
     */
    public static final Tag TAG = Tag.TAG;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>public.user_ability</code>.
     */
    public static final UserAbility USER_ABILITY = UserAbility.USER_ABILITY;
}
