/*
 * This file is generated by jOOQ.
 */
package task.NewOpportunityPortal.db;


import javax.annotation.processing.Generated;

import task.NewOpportunityPortal.db.tables.Adverts;
import task.NewOpportunityPortal.db.tables.Category;
import task.NewOpportunityPortal.db.tables.Chats_;
import task.NewOpportunityPortal.db.tables.Comments_;
import task.NewOpportunityPortal.db.tables.Messages__;
import task.NewOpportunityPortal.db.tables.Status;
import task.NewOpportunityPortal.db.tables.Tag;
import task.NewOpportunityPortal.db.tables.User;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.adverts</code>.
     */
    public static final Adverts ADVERTS = Adverts.ADVERTS;

    /**
     * The table <code>public.category</code>.
     */
    public static final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>public.chats_</code>.
     */
    public static final Chats_ CHATS_ = Chats_.CHATS_;

    /**
     * The table <code>public.comments_</code>.
     */
    public static final Comments_ COMMENTS_ = Comments_.COMMENTS_;

    /**
     * The table <code>public.messages__</code>.
     */
    public static final Messages__ MESSAGES__ = Messages__.MESSAGES__;

    /**
     * The table <code>public.status</code>.
     */
    public static final Status STATUS = Status.STATUS;

    /**
     * The table <code>public.tag</code>.
     */
    public static final Tag TAG = Tag.TAG;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;
}
